package io.github.sixzleo.tabfold.projection;
import android.opengl.GLES20;
// Generated from the established live renderer by tools/sync_dual_renderer.py.
final class FixedDualGpuProgram {
    static final String VERT="attribute vec2 pos; varying vec2 uv; void main(){gl_Position=vec4(pos,0.,1.);uv=vec2((pos.x+1.)*.5,(1.-pos.y)*.5);}";
    static final String FOLD_FRAG="#extension GL_OES_EGL_image_external : require\nprecision highp float;uniform samplerExternalOES nativeSource;uniform mat4 nativeTex;uniform sampler2D level0,level1,level2,level3,level4,level5,level6;uniform float bufferSize,contentScale,canvasSize,contentFraction,bandMix,bandClear;uniform float tilt,crop,inner,turn,opacity,blurStrength,spillFraction,hingeDistanceFraction,screenDarkness,screenFadeActive;uniform vec2 screen;varying vec2 uv;"
        +"vec2 canonical(vec2 p){if(turn<.5)return p;if(turn<1.5)return vec2(1.-p.y,p.x);if(turn<2.5)return vec2(1.-p.x,1.-p.y);return vec2(p.y,1.-p.x);}"
        +"vec2 toScreen(vec2 p){if(turn<.5)return p;if(turn<1.5)return vec2(p.y,1.-p.x);if(turn<2.5)return vec2(1.-p.x,1.-p.y);return vec2(1.-p.y,p.x);}"
        +"vec3 layer(vec2 p,float l){vec3 c;if(l<.5)c=texture2D(level0,p).rgb;else if(l<1.5)c=texture2D(level1,p).rgb;else if(l<2.5)c=texture2D(level2,p).rgb;else if(l<3.5)c=texture2D(level3,p).rgb;else if(l<4.5)c=texture2D(level4,p).rgb;else if(l<5.5)c=texture2D(level5,p).rgb;else c=texture2D(level6,p).rgb;return pow(c,vec3(2.2));}"
        +"vec3 at(vec2 p,float sigma){p=toScreen(p);float y=p.y;float cf=contentFraction;float yS=y>cf?cf+(cf-y)*bandMix:y;p=vec2(p.x,yS/max(cf,.0001));if(sigma<.001){float band=clamp((y-cf)/max(1.-cf,.0001),0.,1.);if(band>0.){vec2 px=vec2(1./screen.x,1./screen.y);float r=4.+30.*band;vec3 c=texture2D(nativeSource,(nativeTex*vec4(p.x,1.-p.y,0.,1.)).xy).rgb;for(int k=0;k<12;k++){float ang=.5236*float(k);float rad=(k-k/2*2)==0?r:r*.5;c+=texture2D(nativeSource,(nativeTex*vec4(p.x+cos(ang)*rad*px.x,1.-p.y+sin(ang)*rad*px.y,0.,1.)).xy).rgb;}return c/13.;}return texture2D(nativeSource,(nativeTex*vec4(p.x,1.-p.y,0.,1.)).xy).rgb;}vec2 extent=screen/max(screen.x,screen.y);p=(1.-extent)*.5+p*extent;p=(1.-contentScale)*.5+p*contentScale;p.y=1.-p.y;float variance=sigma*sigma;float l=clamp(.5*log2(1.+3.*variance/2.854),0.,6.);float lo=floor(l);float a=2.854*(pow(4.,lo)-1.)/3.;float b=2.854*(pow(4.,min(lo+1.,6.))-1.)/3.;float f=clamp((variance-a)/max(b-a,.0001),0.,1.);return pow(mix(layer(p,lo),layer(p,min(lo+1.,6.)),f),vec3(1./2.2));}"
        +"vec4 composite(vec3 color,float alpha,vec2 u){float cf=mix(1.,contentFraction,bandMix);float strip=clamp((toScreen(u).y-cf)/max(1.-cf,.0001),0.,1.);float bandA=1.-strip*bandClear;float dim=1.-(.22+.4*strip)*strip;color*=dim;if(screenFadeActive>.5){vec3 c=mix(at(u,0.),color,alpha)*(1.-screenDarkness);return vec4(c*dim*bandA,bandA);}return vec4(color*alpha*bandA,alpha*bandA);}"
        +"void main(){if(screenDarkness>.999){gl_FragColor=vec4(0.,0.,0.,1.);return;}vec2 p=canvasSize>0.?uv*canvasSize/screen:uv;if(p.x>1.||p.y>1.){gl_FragColor=vec4(0.);return;}vec2 u=canonical(p);if(opacity<.001){gl_FragColor=composite(vec3(0.),0.,u);return;}float W=inner>.5?.146:.073;float x=(u.x-(inner>.5?.5:0.))*W;float y=(u.y-.5)*.16;float spill=inner>.5?.073*spillFraction*sin(tilt):0.;if(inner>.5&&x>=0.&&(spill<=.000001||x>=spill)){gl_FragColor=composite(vec3(0.),0.,u);return;}float coverage=inner>.5&&x>0.?1.-smoothstep(0.,max(spill,.000001),x):1.;if(tilt==0.&&crop==0.){gl_FragColor=composite(at(u,0.),opacity*coverage,u);return;}float paperX=inner>.5?min(x,0.):x;vec3 P=vec3(paperX*cos(tilt),y,abs(paperX)*sin(tilt));vec3 D=normalize(P-vec3(inner>.5?0.:.0365,0.,.6));float t=-P.z/min(D.z,-.0001);vec3 Q=P+t*D;vec2 paperQ=vec2(Q.x/W+(inner>.5?.5:0.),Q.y/.16+.5);float a=clamp(abs(x)/.073,0.,1.);vec2 q=inner>.5&&x>=0.?u:vec2((inner>.5?.5:0.)+x*(1.-crop*a)/W,u.y);float blurGap=t;if(inner>.5){float d=max(spill-x,0.)/(1.+spill/.073);vec3 B=vec3(-d*cos(tilt),y,d*sin(tilt));blurGap=length(B-vec3(0.,0.,.6))*B.z/(.6-B.z);}else{float d=.073*hingeDistanceFraction+abs(x)*(1.-hingeDistanceFraction);vec3 B=vec3(d*cos(tilt),y,d*sin(tilt));blurGap=length(B-vec3(.0365,0.,.6))*B.z/(.6-B.z);}"
        +"float s=min(.03,max(blurGap,0.)*(inner>.5?.55:.75));vec2 canonicalSize=mod(turn,2.)<.5?screen:screen.yx;float sigma=s*canonicalSize.x/max(screen.x,screen.y)*bufferSize*contentScale*blurStrength;"
        // Only top/bottom contours recede; rounded corners meet the pinned sides.
        +"vec2 pixelScale=canonicalSize/max(screen.x,screen.y)*bufferSize*contentScale;float edgeY=min(paperQ.y,1.-paperQ.y)*pixelScale.y;float sideDistance=min(u.x,1.-u.x)*pixelScale.x;float leafPixels=.073/W*pixelScale.x;float radius=leafPixels*.055*sin(tilt);float cornerX=max(radius-sideDistance,0.);float cornerInset=radius-sqrt(max(radius*radius-cornerX*cornerX,0.));float boundary=cornerInset-edgeY;"
        +"float band=max(leafPixels*.18,1.);float inward=max(-boundary,0.)/band;float influence=exp(-.5*inward*inward);float edgeSigma=leafPixels*.025*sin(tilt)*blurStrength*coverage;sigma*=1.4;float baseVariance=sigma*sigma;float edgeVariance=edgeSigma*edgeSigma;float paperSigma=min(62.,sqrt(baseVariance+edgeVariance));sigma=min(62.,sqrt(baseVariance+edgeVariance*influence*influence));vec3 c=at(q,sigma);float feather=max(paperSigma*3.2,.5);float paper=mix(1.,smoothstep(-feather,feather,-boundary),coverage);c*=paper;"
        +"float alpha=opacity*coverage;gl_FragColor=composite(c,alpha,u);}";
    static int shader(int type,String code){int s=GLES20.glCreateShader(type);GLES20.glShaderSource(s,code);GLES20.glCompileShader(s);int[] ok=new int[1];GLES20.glGetShaderiv(s,GLES20.GL_COMPILE_STATUS,ok,0);if(ok[0]==0)throw new IllegalStateException(GLES20.glGetShaderInfoLog(s));return s;}
}
