// Generated by tools/sync_dual_renderer.py; source adaptation only.
package io.github.sixzleo.tabfold.projection;

import android.opengl.*;
import java.nio.FloatBuffer;

/** Reusable real-time Gaussian levels. No readback, buffer resizing or source-frame waits. */
final class FixedDualGpuPyramid {
    static final int LEVELS=7;
    static final float CONTENT_SCALE=.88f;
    final int[] levels=new int[LEVELS],scratch=new int[LEVELS],sizes=new int[LEVELS];
    final int framebuffer,copy,blur;
    final int copyPos,blurPos,copySource,copyScale,copyExtent,copyAxis,copyTexel,copyMatrix,blurSource,blurStep;
    private int boundProgram,renderPos,renderSize,renderScale;
    private final int[] renderLevels=new int[LEVELS];
    private boolean verified;
    final FloatBuffer vertices;
    // Extend source colors across the canonical left/right sides before blur.
    // Only top/bottom retain black padding for the receding paper contour.
    static final String COPY="#extension GL_OES_EGL_image_external : require\nprecision highp float;uniform samplerExternalOES source;uniform mat4 tex;uniform float contentScale,sourceTexel,horizontalAxis;uniform vec2 screenExtent;varying vec2 uv;void main(){vec2 p=(uv-(1.-contentScale)*.5)/contentScale;vec2 lo=(1.-screenExtent)*.5+sourceTexel;vec2 hi=1.-lo;if(horizontalAxis<.5)p.x=clamp(p.x,lo.x,hi.x);else p.y=clamp(p.y,lo.y,hi.y);if(p.x<0.||p.y<0.||p.x>1.||p.y>1.){gl_FragColor=vec4(0.,0.,0.,1.);return;}vec2 edge=(1.-screenExtent)*.5;if(horizontalAxis<.5&&(p.y<edge.y||p.y>1.-edge.y)||horizontalAxis>.5&&(p.x<edge.x||p.x>1.-edge.x)){gl_FragColor=vec4(0.,0.,0.,1.);return;}p=(p-edge)/screenExtent;gl_FragColor=texture2D(source,(tex*vec4(p.x,1.-p.y,0.,1.)).xy);}";
    static final String BLUR="precision highp float;uniform sampler2D source;uniform vec2 stepSize;varying vec2 uv;"
        +"vec3 read(vec2 p){return pow(texture2D(source,p).rgb,vec3(2.2));}"
        +"void main(){vec2 p=vec2(uv.x,1.-uv.y);vec3 c=read(p)*.227027027;"
        +"c+=(read(p+stepSize*1.384615385)+read(p-stepSize*1.384615385))*.316216216;"
        +"c+=(read(p+stepSize*3.230769231)+read(p-stepSize*3.230769231))*.070270270;"
        +"gl_FragColor=vec4(pow(max(c,vec3(0.)),vec3(1./2.2)),1.);}";
    FixedDualGpuPyramid(int size,FloatBuffer vertices){
        this.vertices=vertices;copy=program(COPY);blur=program(BLUR);
        copyPos=GLES20.glGetAttribLocation(copy,"pos");blurPos=GLES20.glGetAttribLocation(blur,"pos");
        copySource=GLES20.glGetUniformLocation(copy,"source");copyScale=GLES20.glGetUniformLocation(copy,"contentScale");
        copyExtent=GLES20.glGetUniformLocation(copy,"screenExtent");copyAxis=GLES20.glGetUniformLocation(copy,"horizontalAxis");
        copyTexel=GLES20.glGetUniformLocation(copy,"sourceTexel");copyMatrix=GLES20.glGetUniformLocation(copy,"tex");
        blurSource=GLES20.glGetUniformLocation(blur,"source");blurStep=GLES20.glGetUniformLocation(blur,"stepSize");
        int[] f=new int[1];GLES20.glGenFramebuffers(1,f,0);framebuffer=f[0];
        GLES20.glGenTextures(LEVELS,levels,0);GLES20.glGenTextures(LEVELS-1,scratch,1);
        for(int i=0;i<LEVELS;i++){
            sizes[i]=Math.max(1,(size+(1<<i)-1)>>i);
            allocate(levels[i],sizes[i]);if(i>0)allocate(scratch[i],sizes[i]);
        }
    }
    static int program(String fragment){
        int p=GLES20.glCreateProgram();
        int v=FixedDualGpuProgram.shader(GLES20.GL_VERTEX_SHADER,FixedDualGpuProgram.VERT);
        int f=FixedDualGpuProgram.shader(GLES20.GL_FRAGMENT_SHADER,fragment);
        GLES20.glAttachShader(p,v);GLES20.glAttachShader(p,f);GLES20.glLinkProgram(p);
        GLES20.glDeleteShader(v);GLES20.glDeleteShader(f);
        int[] ok=new int[1];GLES20.glGetProgramiv(p,GLES20.GL_LINK_STATUS,ok,0);
        if(ok[0]==0)throw new IllegalStateException(GLES20.glGetProgramInfoLog(p));return p;
    }
    static void allocate(int texture,int size){
        GLES20.glBindTexture(GLES20.GL_TEXTURE_2D,texture);
        GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D,GLES20.GL_TEXTURE_MIN_FILTER,GLES20.GL_LINEAR);
        GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D,GLES20.GL_TEXTURE_MAG_FILTER,GLES20.GL_LINEAR);
        GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D,GLES20.GL_TEXTURE_WRAP_S,GLES20.GL_CLAMP_TO_EDGE);
        GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D,GLES20.GL_TEXTURE_WRAP_T,GLES20.GL_CLAMP_TO_EDGE);
        GLES20.glTexImage2D(GLES20.GL_TEXTURE_2D,0,GLES20.GL_RGBA,size,size,0,GLES20.GL_RGBA,GLES20.GL_UNSIGNED_BYTE,null);
    }
    void target(int texture,int size,int program){
        GLES20.glBindFramebuffer(GLES20.GL_FRAMEBUFFER,framebuffer);
        GLES20.glFramebufferTexture2D(GLES20.GL_FRAMEBUFFER,GLES20.GL_COLOR_ATTACHMENT0,GLES20.GL_TEXTURE_2D,texture,0);
        if(!verified&&GLES20.glCheckFramebufferStatus(GLES20.GL_FRAMEBUFFER)!=GLES20.GL_FRAMEBUFFER_COMPLETE)throw new IllegalStateException("Blur framebuffer incomplete");
        GLES20.glViewport(0,0,size,size);GLES20.glUseProgram(program);
        int pos=program==copy?copyPos:blurPos;vertices.position(0);
        GLES20.glEnableVertexAttribArray(pos);GLES20.glVertexAttribPointer(pos,2,GLES20.GL_FLOAT,false,0,vertices);
    }
    void update(int external,float[] matrix,int screenWidth,int screenHeight,int turn){
        GLES20.glActiveTexture(GLES20.GL_TEXTURE7);GLES20.glBindTexture(GLES11Ext.GL_TEXTURE_EXTERNAL_OES,external);
        target(levels[0],sizes[0],copy);GLES20.glUniform1i(copySource,7);
        GLES20.glUniform1f(copyScale,CONTENT_SCALE);
        float longest=Math.max(screenWidth,screenHeight);
        GLES20.glUniform2f(copyExtent,screenWidth/longest,screenHeight/longest);
        GLES20.glUniform1f(copyAxis,turn%2);
        GLES20.glUniform1f(copyTexel,1f/sizes[0]);
        GLES20.glUniformMatrix4fv(copyMatrix,1,false,matrix,0);GLES20.glDrawArrays(GLES20.GL_TRIANGLE_STRIP,0,4);
        GLES20.glActiveTexture(GLES20.GL_TEXTURE0);
        for(int i=1;i<LEVELS;i++){
            target(scratch[i],sizes[i],blur);GLES20.glBindTexture(GLES20.GL_TEXTURE_2D,levels[i-1]);
            GLES20.glUniform1i(blurSource,0);
            GLES20.glUniform2f(blurStep,1f/sizes[i],0);GLES20.glDrawArrays(GLES20.GL_TRIANGLE_STRIP,0,4);
            target(levels[i],sizes[i],blur);GLES20.glBindTexture(GLES20.GL_TEXTURE_2D,scratch[i]);
            GLES20.glUniform2f(blurStep,0,1f/sizes[i]);GLES20.glDrawArrays(GLES20.GL_TRIANGLE_STRIP,0,4);
        }
        GLES20.glBindFramebuffer(GLES20.GL_FRAMEBUFFER,0);
        verified=true;
    }
    void bind(int program,int width,int height){
        if(boundProgram!=program){
            boundProgram=program;renderPos=GLES20.glGetAttribLocation(program,"pos");
            renderSize=GLES20.glGetUniformLocation(program,"bufferSize");renderScale=GLES20.glGetUniformLocation(program,"contentScale");
            for(int i=0;i<LEVELS;i++)renderLevels[i]=GLES20.glGetUniformLocation(program,"level"+i);
        }
        GLES20.glUseProgram(program);GLES20.glViewport(0,0,width,height);
        int pos=renderPos;vertices.position(0);
        GLES20.glEnableVertexAttribArray(pos);GLES20.glVertexAttribPointer(pos,2,GLES20.GL_FLOAT,false,0,vertices);
        for(int i=0;i<LEVELS;i++){GLES20.glActiveTexture(GLES20.GL_TEXTURE0+i);GLES20.glBindTexture(GLES20.GL_TEXTURE_2D,levels[i]);GLES20.glUniform1i(renderLevels[i],i);}
        GLES20.glUniform1f(renderSize,sizes[0]);
        GLES20.glUniform1f(renderScale,CONTENT_SCALE);
        GLES20.glActiveTexture(GLES20.GL_TEXTURE0);
    }
    void close(){GLES20.glDeleteTextures(LEVELS,levels,0);GLES20.glDeleteTextures(LEVELS,scratch,0);GLES20.glDeleteFramebuffers(1,new int[]{framebuffer},0);GLES20.glDeleteProgram(copy);GLES20.glDeleteProgram(blur);}
}
