from pathlib import Path
root=Path(__file__).resolve().parents[1]
base=root/"projection-lab/src/main/java/io/github/sixzleo/tabfold/projection"
source=(root/"tools/helpers/LiveMirrorWindowProbe.java").read_text(encoding="utf-8")
vert=source[source.index("    static final String VERT="):source.index("    static final String FRAG=")]
fold=source[source.index("    static final String FOLD_FRAG="):source.index("    public static void main(")]
# Clear pixels must bypass the reduced Gaussian pyramid and sample the native task buffer.
fold=fold.replace('FOLD_FRAG="precision highp float;', 'FOLD_FRAG="#extension GL_OES_EGL_image_external : require\\nprecision highp float;uniform samplerExternalOES nativeSource;uniform mat4 nativeTex;')
fold=fold.replace('vec3 at(vec2 p,float sigma){p=toScreen(p);', 'vec3 at(vec2 p,float sigma){p=toScreen(p);if(sigma<.001)return texture2D(nativeSource,(nativeTex*vec4(p.x,1.-p.y,0.,1.)).xy).rgb;')
shader=source[source.index("    static int shader("):source.index("    static void render(")]
(base/"FixedDualGpuProgram.java").write_text("package io.github.sixzleo.tabfold.projection;\nimport android.opengl.GLES20;\n// Generated from the established live renderer by tools/sync_dual_renderer.py.\nfinal class FixedDualGpuProgram {\n"+vert+fold+shader+"}\n",encoding="utf-8")
pyramid=(root/"tools/helpers/LiveBlurPyramid.java").read_text(encoding="utf-8").replace("package io.github.sixzleo.tabfold.probe;","package io.github.sixzleo.tabfold.projection;").replace("LiveBlurPyramid","FixedDualGpuPyramid").replace("LiveMirrorWindowProbe","FixedDualGpuProgram")
# The live mirror source is letterboxed in a square. Independent task buffers are rectangular;
# normalize that source rectangle only. Gaussian levels, gamma, interpolation and drawing stay shared.
pyramid=pyramid.replace('gl_FragColor=texture2D(source,(tex*vec4(p.x,1.-p.y,0.,1.)).xy);}',
    'vec2 edge=(1.-screenExtent)*.5;if(horizontalAxis<.5&&(p.y<edge.y||p.y>1.-edge.y)||horizontalAxis>.5&&(p.x<edge.x||p.x>1.-edge.x)){gl_FragColor=vec4(0.,0.,0.,1.);return;}p=(p-edge)/screenExtent;gl_FragColor=texture2D(source,(tex*vec4(p.x,1.-p.y,0.,1.)).xy);}')
(base/"FixedDualGpuPyramid.java").write_text("// Generated by tools/sync_dual_renderer.py; source adaptation only.\n"+pyramid,encoding="utf-8")
